### ISSUE TITLE
Dependency update?

### ISSUE THREAD

**Issue by mensfeld** [rtfpessoa/diff2html-cli#104]
Hey, first of all, thank you for this amazing lib and its maintenance.

I've noticed, that the package.json locks the diff2html to `3.1.6` while there's `3.1.9` ready with some bug fixes. Is there a chance for upgrade?

It does not want to use the newer release with yarn:

```
diff2html-cli@^5.1.1:
  version "5.1.1"
  resolved "https://registry.yarnpkg.com/diff2html-cli/-/diff2html-cli-5.1.1.tgz#f6de2131aca5ca8190aa69f574361212f458a757"
  integrity sha512-toCl99MHN1+jErcwys0DEcDGhF8DDO9C2/WGYQK44oCEKCiTVBKEOD6UJJc7TVL4fYR+zqiH7UZDUiPgH/qD4Q==
  dependencies:
    clipboardy "^2.3.0"
    diff2html "3.1.6"
    node-fetch "^2.6.0"
    open "^7.0.3"
    yargs "^15.3.1"
```

**Comment by rtfpessoa** [comment]
Released as version ` 5.1.2`

**Comment by mensfeld** [comment]
Woooooo that was quick. Thank you sooooooo much! You are amazing (seriously)!

**Comment by rtfpessoa** [comment]
I was planning to do some maintenance and since you remembered me I just did it immediatly 😃
