### ISSUE TITLE
Unescaped broken HTML in the output

### ISSUE THREAD

**Issue by mensfeld** [rtfpessoa/diff2html-cli#106]
Hello again, this time a bug report:

Repro:

```
git clone https://github.com/mensfeld/broken-diff.git
cd https://github.com/mensfeld/broken-diff.git
./run.sh
```
browser will open and then scroll to file called ` web/assets/javascripts/application.js ` it looks as followed:

![Zrzut ekranu z 2020-07-24 18-08-07](https://user-images.githubusercontent.com/392754/88413641-cd0dff80-cddb-11ea-98f4-e0ef825aeaa3.png)

while on a really, really old version of this cli (`2.7.0`), it looks like so:

![Zrzut ekranu z 2020-07-24 18-08-48](https://user-images.githubusercontent.com/392754/88413660-d6976780-cddb-11ea-83d0-073b8535a102.png)

**Comment by rtfpessoa** [comment]
Wow, some bad thing going on here.
Seems like in was introduced in version `5.0.0`. Last version where is seems fine is `4.2.1`.

**Comment by rtfpessoa** [comment]
Reinstalling `diff2html-cli` should be enough to get the new version from `diff2html`.

Seems to work fine in the demo: https://diff2html.xyz/demo.html?matching=none&matchWordsThreshold=0.25&maxLineLengthHighlight=10000&diffStyle=word&renderNothingWhenEmpty=0&matchingMaxComparisons=2500&maxLineSizeInBlockForComparison=200&outputFormat=line-by-line&drawFileList=1&synchronisedScroll=1&highlight=1&fileListToggle=1&fileListStartVisible=0&smartSelection=1&diff=https://github.com/mensfeld/broken-diff/commit/8750ece41b3e89d9f8497f062458d826cdd79d6f#d2h-719103

**Comment by mensfeld** [comment]
Hey @rtfpessoa any idea what I can do beyond removing the `node_modules` from my project? I tried that, reinstalled and seeing same effects :(

cleaning yarn cache does not help as well

**Comment by rtfpessoa** [comment]
Weird. I just did `yarn global remove diff2html-cli` and then `yarn global add diff2html-cli`.

If it is local to a repository I was expecting that `yarn remove diff2html-cli` followed by `yarn add diff2html-cli` would do it.

Can you try adding `--force` and see if it works?
If not I will add a new version. I was really expecting the `^3.x.x` to allow minor and patch updated automatically.

**Comment by mensfeld** [comment]
@rtfpessoa please forgive me for pinging you prematurely. I forgot to update the `yarn.lock` file, thus it was pointing to the old version of diff2html. After purging, cleaning and forcing things work great.

Once again: thank you for your amazing work!

**Comment by rtfpessoa** [comment]
No worries. Nice that it worked.
