### ISSUE TITLE
diff2html is missing file content toggle 

### ISSUE THREAD

**Issue by maxvisser** [rtfpessoa/diff2html-cli#135]
As I saw that this feature was added and in the demo. I looked into the code on how to enable it.

<img width="199" alt="image" src="https://user-images.githubusercontent.com/10818702/167595363-cbf27359-1834-47bc-9418-c9f1a5f4bea9.png">

I opened a pull request
https://github.com/rtfpessoa/diff2html-cli/pull/134

**Comment by rtfpessoa** [comment]
Thank you for the contribution
