### ISSUE TITLE
--title option not working

### ISSUE THREAD

**Issue by ggft-ggft** [rtfpessoa/diff2html-cli#136]
Hello, I'm trying using with the '--title' option but it does not seem to work in the output html.

Example:

![image](https://user-images.githubusercontent.com/61045136/168630756-d45881ef-96bd-410a-b220-fa16dd63c77c.png)

Output:

![image](https://user-images.githubusercontent.com/61045136/168630837-e4cf0315-9087-4a8e-9ca2-cc99c7c4d0ac.png)

I installed the cli tool with `npm install -g diff2html-cli`

Thank you

**Comment by rtfpessoa** [comment]
Thanks for reporting. Fix here https://github.com/rtfpessoa/diff2html-cli/pull/137

I never had tested this myself and did only a eye review. 🤦

**Comment by rtfpessoa** [comment]
Released as version `5.2.3`
