### ISSUE TITLE
error when given 0 byte file (windows?)

### ISSUE THREAD

**Issue by sreich** [rtfpessoa/diff2html-cli#15]
me again :)

i'm not sure if this is a platform specific issue, but i'm leaving the option open, given the other issues i ran into on this platform

if i give it a 0 byte file, which on windows was generated from something like 'hg diff -r rev1:rev2 > thing.diff', and converted using dos2unix to unix line endings...(horrible i know, but this utility chokes on them too..for which i will file another issue)

the following happens:

└─[$] diff2html.cmd -F TESTHTML.html -i file -- thing.diff                                                                               [8:36:47]
The input is empty. Try again.
C:\Users\sreich\AppData\Roaming\npm\node_modules\diff2html-cli\src\main.js:141
    argv.help();
         ^

TypeError: argv.help is not a function
    at onInput (C:\Users\sreich\AppData\Roaming\npm\node_modules\diff2html-cli\src\main.js:141:10)
    at FSReqWrap.readFileAfterClose [as oncomplete](fs.js:380:3)

i'm not sure exactly how to reproduce this differently. i tried just doing 'touch thing.diff', but that didn't seem to make it choke up.

**Comment by rtfpessoa** [comment]
Weird, it gave you the message `The input is empty. Try again.` but still it crashed. Need to check.

Just so you do not think I am skipping this, I am taking note of the issues and when I have time I will look into them.

Still if you want I am always look for some help with prs.

**Comment by rtfpessoa** [comment]
@sreich fixed in [https://github.com/rtfpessoa/diff2html-cli/commit/534fdd8d861610420ee61f86f7941cee31450b8f](https://github.com/rtfpessoa/diff2html-cli/commit/534fdd8d861610420ee61f86f7941cee31450b8f) released as version `1.4.1`.
