### ISSUE TITLE
generates empty html file when diff has windows line endings (CRLF)

### ISSUE THREAD

**Issue by sreich** [rtfpessoa/diff2html-cli#16]
when the diff diff2html-cli is given, has CRLF line endings, the generator will generate a valid html file, but it will act as if the source diff was empty.

obviously, this isn't ideal on windows -- especially when everything is so hard coded (cmd, powershell) to always output \r\n.

i'm not sure how fixable this is for you, or if it touches the entire code base (hope not). presently i'm running dos2unix on the diffs i create from hg, but of course that is a real hack and has its own pitfalls.

**Comment by pbu88** [comment]
I've run into this issue too when implementing diffy. I basically fixed it on my end by turning CRLF into LF only but I think it won't hurt to fix the parser to address this case (this issue actually belongs in diff2html) :)

**Comment by rtfpessoa** [comment]
Moving this to [https://github.com/rtfpessoa/diff2html/issues/57](https://github.com/rtfpessoa/diff2html/issues/57)
