### ISSUE TITLE
Takes hours for finish a 300kb diff file.

### ISSUE THREAD

**Issue by efurban** [rtfpessoa/diff2html-cli#17]
HI, 
I really love the tool and currently running it under windows. 
however my git diff file is around 300KB, the tool takes 3 hours to finish , without any output file (am using -F option).   memory usage is around 800MB.  
Just wondering if you have encountered the same issue before?  

Tried diffy.org  without no issues at all.  
https://diffy.org/diff/4wng00ndqz7iudi

thanks. 
Travis 
[diffReport.txt](https://github.com/rtfpessoa/diff2html-cli/files/215870/diffReport.txt)

**Comment by rtfpessoa** [comment]
Can you test with `npm install -g diff2html-cli@1.4.2`, it was before nunjucks was added.

Let me know if it helps

**Comment by pbu88** [comment]
Tried different combinations with the latest versions of everything and it seemed to work pretty fast, including this command: `bin/diff2html -i file -F  xx ~/Downloads/diffReport.txt` and everything worked pretty fast. Can you share the exact version you are using of diff2html-cli and diff2html and the exact command that you are using to call it?

Thanks

**Comment by efurban** [comment]
I should have mentioned that I am on a Windows machine and running this in git bash. 
did try the combinations of all of the following: 
node.js v.5.10.1 Stable
node.js v.4.4.2 LTS
node-v0.10.28-x86
diff2html-cli@1.4.2
diff2html-cli@1.4.6-beta3

Command that I am calling: 
diff2html --file diff.html --style line --summary open --input file -- diffReport.txt

Any ideas?  maybe I should build a Linux box?

**Comment by efurban** [comment]
It works perfectly for smaller diff though. 
@ 04/13/2016 9:29 AM
tried on a different Windows 7 machine. same outcome.

**Comment by efurban** [comment]
got an ubuntu running and tested it with the same command but with the issue.  see the screenshot below: 
http://screencast.com/t/peNOkYhnss

eventually it came back with error: 
FATAL ERROR: CALL_AND_RETRY_2 Allocation failed - process out of memory

**Comment by rtfpessoa** [comment]
I think I have the same problem. I will look into this.

**Comment by pbu88** [comment]
Hmm strange, I haven't been able to reproduce it on Mac OSX. For me it works fast.

**Comment by rtfpessoa** [comment]
I just tried with his command, and his file and I got stuck, on OS X.
Will do some debugging.

**Comment by efurban** [comment]
thanks a lot rtfpessoa.

**Comment by rtfpessoa** [comment]
So just got it.

The `Rematch.distance(amod, bmod)` algorithm is taking too long, and maybe getting an infinite loop or something.

I will move this to [diff2html](https://github.com/rtfpessoa/diff2html).

@efurban In the meanwhile try to run this with `--lm none`

**Comment by efurban** [comment]
--lm none  worked!!  thanks a lot guys. 
Really love this tool.

**Comment by rtfpessoa** [comment]
This was fixed in diff2html.
