### ISSUE TITLE
It is probably worth to mention in docs that it expects unified diff

### ISSUE THREAD

**Issue by andruhon** [rtfpessoa/diff2html-cli#18]
Say 
`diff -u fileA.txt fileB.txt | diff2html -F diff.html -i stdin`

But not
`diff fileA.txt fileB.txt | diff2html -F diff.html -i stdin`

**Comment by rtfpessoa** [comment]
Hi @andruhon, until a couple of weeks ago it only supported git diffs. Then I added support for unified diffs but I did not update the docs. I will try to do it soon, with better explanation.

**Comment by rtfpessoa** [comment]
Fixed
