### ISSUE TITLE
Synchronised scroll doesn't work

### ISSUE THREAD

**Issue by mkurz** [rtfpessoa/diff2html-cli#22]
Using `diff2html -s side --sc enabled` or `diff2html --synchronisedScroll enabled -s side`

**Comment by rtfpessoa** [comment]
There was a problem with config usage. Should be fixed in v2.0.5.

**Comment by mkurz** [comment]
Thanks, will give it a shot tomorrow.

**Comment by mkurz** [comment]
Thank you, it worked!
