### ISSUE TITLE
doesn't work with diff?

### ISSUE THREAD

**Issue by greggman** [rtfpessoa/diff2html-cli#23]
Maybe I'm mis-understanding the docs but I tried using `diff` to generate a `.diff` file and then using `diff2html` but it shows no diffs

```
$ cat > file1.txt
1
2
3
4
5
^D
$ cat > file2.txt
1
2
9
4
5
^D
$ diff file1.txt file2.txt
3c3
< 3
---
> 9
$ diff file1.txt file2.txt > test.diff
$ diff2html -i file -- test.diff
$ 
```

the result is this

![screen shot 2017-04-20 at 6 02 58 pm](https://cloud.githubusercontent.com/assets/234804/25222517/a252d61e-25f3-11e7-8490-770a30047c04.png)

Is it supposed to work with diff files?

**Comment by rtfpessoa** [comment]
The tool only supports `unified diff` or `git diff`. You can do for example `git diff --no-index file1 file2` (even without a git repo). `diff` probably also has a flag to output unified diff.

**Comment by greggman** [comment]
Oh, haha.  I read this

> Unified diff and Git diff input

as "unified input of both diff and Git diff" 😅

**Comment by rtfpessoa** [comment]
np 😄

**Comment by pbu88** [comment]
You can also use `diff` with the `-u` switch. Basically it tells diff to output in a unified diff format.

**Comment by rtfpessoa** [comment]
That is probably it. Thanks @pbu88
