### ISSUE TITLE
"The input is empty" error in an all-committed git repo

### ISSUE THREAD

**Issue by kaushalmodi** [rtfpessoa/diff2html-cli#26]
When running `diff2html` in a non-dirty git repo (where everything has been committed), I get:

> The input is empty. Try again.

Should `diff2html` default to `diff2html HEAD~1` in that case?

**Comment by rtfpessoa** [comment]
In the past I had that behavior but it was a bit confusing. For that reason I removed it.

Unless we have a big reason I would prefer not to change it.
