### ISSUE TITLE
Improve alignment of diff2html -h

### ISSUE THREAD

**Issue by kaushalmodi** [rtfpessoa/diff2html-cli#27]
When I type `diff2html -h`, I see:
![image](https://cloud.githubusercontent.com/assets/3578197/25981464/59bc7eee-36a3-11e7-97d4-3d4c5a1ae2fe.png)

I find the lack of column-based alignment make the output difficult to read. Compare to other CLI utility help outputs like `grep --help`:
![image](https://cloud.githubusercontent.com/assets/3578197/25981510/99e7a2fa-36a3-11e7-9fd3-175fa9f6ea67.png)

---

Can you please format the output into clean columns?

**Comment by rtfpessoa** [comment]
The output is provided by `yargs` and I am not sure there is an option for that. If you find a way to do that I would gladly use it. But `yargs` has provided a great abstraction over the args so I really would not be willing to change unless there is a really good reason for it.

**Comment by rtfpessoa** [comment]
If we find any solution I can re-open this.
