### ISSUE TITLE
seems don't support property change

### ISSUE THREAD

**Issue by lzq420241** [rtfpessoa/diff2html-cli#28]
for example, when the input is:
<div>
Property changes on: a.c
___________________________________________________________________<br>
Added: svn:executable<br>
## -0,0 +1 ##<br>
+*<br>
\ No newline at end of property<br>
Index:a.c<br>
===================================================================<br>
the output html is:<br>
 + * <br>
</div>

what I expected is:
src/{a.c (revision 1, filemode 100644) -> src/{a.c (revision 2, filemode 100744)

**Comment by rtfpessoa** [comment]
Hi @lzq420241,

That is not a valid unified diff. There is an open pr to support that diff but the owner is not updating it here https://github.com/rtfpessoa/diff2html/pull/125
