### ISSUE TITLE
Feature Request - cmdline argument to set the report title in the html 

### ISSUE THREAD

**Issue by schaveyt** [rtfpessoa/diff2html-cli#33]
I am working on documentation that is production released within our company and we started using this great utility. One of the things we need to do after the report is created is manually alter the text of the title and use the sed utility to change it.

What are your thoughts for a request to allow the user to specify the text of the tile via the commandline?

**Comment by rtfpessoa** [comment]
@schaveyt I think that  should be ok. You are the first person that brought that up.
Feel free to send a PR.

**Comment by schaveyt** [comment]
Saweet! Will give the new release a shot.
