### ISSUE TITLE
change page title

### ISSUE THREAD

**Issue by ceduliocezar** [rtfpessoa/diff2html-cli#34]
It is not possible to change the title of the output html diff from cli?

By default it displays Diff to HTML by rtfpessoa.

I would like to pass a parameter to  change it, but wasn't able to find it in the docs.

**Comment by rtfpessoa** [comment]
Duplicate of https://github.com/rtfpessoa/diff2html-cli/issues/33

**Comment by eduardocopat** [comment]
I still think there would be value to have a flag to set a title (for example, `--title My Title`).

**Comment by rtfpessoa** [comment]
Feel free to send a PR
