### ISSUE TITLE
New Feature: Use random output file names instead of fixed diff.html

### ISSUE THREAD

**Issue by myelsukov** [rtfpessoa/diff2html-cli#37]
Fixed (default) output file name (e.g. file:///private/var/folders/xz/jt5vrgxj3nb7vnb6hhp8lrvsqy78qg/T/diff.html) makes impossible looking into diffs from different projects at the same time because they override each other.

Please use either random default output file names or make output file name a function of the git repository name.

**Comment by rtfpessoa** [comment]
Feel free to send a PR.
