### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by arijitAD** [rtfpessoa/diff2html-cli#41]
Can you add Dark theme?

**Comment by rtfpessoa** [comment]
@arijitAD PRs are welcome in to https://github.com/rtfpessoa/diff2html. If you want to try start with minimal changes to the current CSS.

**Comment by jdecode** [comment]
Was this implemented?
If not, I can create a PR for this. Didn't find any link to dark mode, except in here (I am assuming this was not done, but please confirm).

Note: I am having the need to integrate in a dark-themed app, so will have to do it anyway, it would be great if I can contribute here as well :)

**Comment by rtfpessoa** [comment]
@jdecode this was not implemented yet.
If you are interested feel free to contribute.
Probably you want to check https://github.com/rtfpessoa/diff2html/issues/191 since CSS might need a fix to get different themes in the code highlight part.
