### ISSUE TITLE
Convert to TypeScript?

### ISSUE THREAD

**Issue by whyboris** [rtfpessoa/diff2html-cli#46]
I'm curious if you think it's worth converting (at least part) of the codebase to _TypeScript_.

The key benefit would be type annotations for method inputs (to make it clear what the methods expect and what types they will return).

I could test out converting a single file to see whether everything works as expected 👌 but only if you think it worth the effort 👍

**Comment by rtfpessoa** [comment]
@whyboris that could be interesting. The only thing I would like to keep would be to have nice compatibility with JS.

**Comment by whyboris** [comment]
I'll give it a try sometime 😁

**Comment by whyboris** [comment]
closed with #53 ✅
