### ISSUE TITLE
Character-by-character highlighting?

### ISSUE THREAD

**Issue by whophil** [rtfpessoa/diff2html-cli#55]
Is there a way to do character by character highlighting in diffs? For example:
![image](https://user-images.githubusercontent.com/2186528/65558077-49009800-deea-11e9-819b-427aca9bdf0f.png)
I would only want the last digit in each number to be dark-highlighted.

**Comment by whophil** [comment]
It looks like this feature was lost with 4.0.0 (exists in 3.0.4 via the `diff2html-cli -d char`)

**Comment by rtfpessoa** [comment]
@whophil thanks for the report. Seems like it got lost in the refactor. Will bring it back.

**Comment by rtfpessoa** [comment]
Released as version `4.2.0`.
Sorry for the regression. For some reason I though the option changed name.
I need to move the diff2html code to TS to make sure these things don't happen.

**Comment by whophil** [comment]
Thanks for the quick fix!
