### ISSUE TITLE
<diff2html-diff> element not working in template specified in --htmlWrapperTemplate

### ISSUE THREAD

**Issue by timblaktu** [rtfpessoa/diff2html-cli#58]
UPDATE: I have confirmed that the "stock" template.html works in my environment. I apologize for the confusion. I suspect the problem is related to how I extended your "author" comment with more text. I would still like some clarification, and ideally some examples, on how these "variables" are to be used. 

diff2html is not substiituting the diff content when I insert <diff2html-diff> element in a  template specified in --htmlWrapperTemplate. I have tried it with the element being a comment and without. I suspect it's a problem with my template file but it's not clear from the documentation how these "variables" are supposed to be used.

I modified [your template](https://github.com/rtfpessoa/diff2html-cli/blob/master/template.html) and have attached the result that I'm using (diff2html-template.html). Here is the command I'm using:

```diff2html --summary open --htmlWrapperTemplate diff2html-template.html --style side -i file -F CHANGELOG-LASTBUILD.html -- CHANGELOG-LASTBUILD.txt```

I can change the content in the h1 tag and see the changes, but that Header is all I see in the generated HTML page. 

The command works great without the --htmlWrapperTemplate option. It would be nice if the provided template.html was a working example and easy for users to modify.

**Expected behavior**
When using --htmlWrapperTemplate option, and including the  element, I expect the diff content to be inserted in the body of the generated html document, and to be able to see the diff content in the browser.

Here's the template I'm using:

```<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Firmware CHANGELOG</title>

    <!--
      Custom Template for Diff2HTML Output
      Taken from https://github.com/rtfpessoa/diff2html-cli

      To be used with --hwt arg.

      Templates can include the following variables:
        <!--diff2html-css--> - writes default CSS to page
        <!--diff2html-js-ui--> - writes default JavaScript UI scripts to page
        //diff2html-fileListCloseable - writes code to support selected list interaction, must be within a <script> block
        //diff2html-synchronisedScroll - writes code to support selected scroll interaction, must be within a <script> block
        <!--diff2html-diff--> - writes diff content to page

    -->

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.9.0/styles/github.min.css" />

    <diff2html-css>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.9.0/highlight.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.9.0/languages/scala.min.js"></script>

    <!--script>
      $(document).ready(function() {
        var diff2htmlUi = new Diff2HtmlUI();
        //diff2html-fileListCloseable
        //diff2html-synchronisedScroll
        //diff2html-highlightCode
      });
    </script-->

  </head>
  <body style="text-align: center; font-family: 'Source Sans Pro',sans-serif;">
    <h1>Firmware CHANGELOG</h1>

    <div id="diff">
      <diff2html-diff>
    </div>
  </body>
</html>
```

**Comment by rtfpessoa** [comment]
@timblaktu let's try to go in parts here.

Regarding how the template works, it is a very basic replace as you can see here https://github.com/rtfpessoa/diff2html-cli/blob/master/src/cli.ts#L40
This will replace the comments in the HTML by the code to perform that action, since they are comments in the first place they won't break if they are not replaced.

Regarding your issue seems like you have the script tag between comment `<!--script>` should be `<script>` and `</script-->` should be `</script>`.

Summary, to achieve a custom template you just need to make sure you have this inside your HTML:
* Inside the `<head>`
```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.9.0/styles/github.min.css" />
<!--diff2html-css-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.9.0/highlight.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.9.0/languages/scala.min.js"></script>
<!--diff2html-js-ui-->
<script>
    $(document).ready(function() {
        var diff2htmlUi = new Diff2HtmlUI();
        //diff2html-fileListCloseable
        //diff2html-synchronisedScroll
        //diff2html-highlightCode
      });
</script>
```
* Inside the `<body>`
```
<div id="diff">
  <!--diff2html-diff-->
</div>
```

If you miss parts of this you will be missing functionality, also make sure you have this code exactly as is.

Everything else you can customize.

Let me know if it works.

**Comment by timblaktu** [comment]
Thanks for the clarification, @rtfpessoa. Yes, the stock template,html is working for me. I see in your code that you're doing a search and replace on the html comment. Maybe the README could be updated to be more explicit in this description, since it currently calls these comments "variables" and does not really describe how they work syntactically.

**Comment by rtfpessoa** [comment]
Improved the docs here https://github.com/rtfpessoa/diff2html-cli/pull/60
Let me know if you would add something else.
