### ISSUE TITLE
Return code should be non-zero on error

### ISSUE THREAD

**Issue by vincentbernat** [rtfpessoa/diff2html-cli#98]
Hey!

When running `diff2html`, I would expect that a fatal error would return a status code different of 0. Currently, the error is printed but the status code says 0.

**Comment by rtfpessoa** [comment]
I guess I never worked on that part. Eventually I should set `process.exitCode`

**Comment by rtfpessoa** [comment]
Check https://github.com/rtfpessoa/diff2html-cli#exit-status-codes for the codes and you can also start using it in version `5.1.0`.

**Comment by vincentbernat** [comment]
Thanks!
